[33기 팀 wantUS] 채용공고 팔로우 기능 추가 (CREATE: Follow View)
wecode-bootcamp-korea/33-2nd-wantUS-backend pull request #14
Opened 2022-06-13 11:13 UTC by jhwang0801

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 채용 공고 팔로우 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
### 1. [POST] Follow 기능 구현(Follow View)
- 로그인 데코레이터를 통해서 user정보 추출
- json data 형식으로 `job_id` 값 전달 받음
- 해당 DB 테이블에 `user_id = user, job_id = job_id` Row가 존재하는 경우, 삭제하고 총 Follow 수 출력
- 해당 DB 테이블에 `user_id = user, job_id = job_id` Row가 존재하지 않는 경우, 해당 데이터 DB에 입력 

### 2. test.py 유닛테스트 결과
![image](https://user-images.githubusercontent.com/75832544/173341727-3f9bef31-e221-41a7-901b-f43348260879.png)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 팔로우 및 다양한 소셜 웹사이트에서 흔히 사용되는 "좋아요" 와 같은 기능구현을 진행하며 개념을 확실히 하게되었습니다.

<br />

## :: 기타 질문 및 특이 사항
- None.

2022-06-13 13:19 UTC, bigfanoftim requested changes

2022-06-13 13:19 UTC, bigfanoftim commented on jobs/views.py
> +        user   = request.user.id
변수명을 좀 더 명확하게 작성하여 여러 메소드의 인자로 넘길 때 휴먼 에러를 줄일 수 있습니다.
이 부분이 정말 사소하지만 타입을 지정하지 않는 파이썬의 경우 특히 더 신경써주셔야 합니다!
```suggestion
        user   = request.user
```

2022-06-13 13:20 UTC, bigfanoftim requested changes

2022-06-13 13:20 UTC, bigfanoftim commented on jobs/views.py
> +        results = True
`get_or_create`를 사용하여 `이미 팔로우가 있으면 삭제, 없으면 생성` 이라는 느낌으로 코드를 작성해볼 수 있지 않을까요?

2022-06-14 05:06 UTC, jhwang0801 commented on jobs/views.py
> +        results = True
`get_or_create()` method는 Django Framework에서만 사용이 가능하다고 알고 있어서,
좋아요나 팔로우 같은 경우 다른 방식으로 작업을 해보고 싶어서 위 코드와 같이 작성해봤습니다!

혹시 연산처리 관련하여 문제가 있기 때문에 method를 사용해야할까요??

2022-06-14 05:06 UTC, jhwang0801 commented on jobs/views.py
> +        user   = request.user.id
수정 완료하였습니다!!

2022-06-14 05:12 UTC, bigfanoftim commented on jobs/views.py
> +        results = True
> get_or_create() method는 Django Framework에서만 사용이 가능하다고 알고 있어서,
좋아요나 팔로우 같은 경우 다른 방식으로 작업을 해보고 싶어서 위 코드와 같이 작성해봤습니다!

위와 같은 이유라면 괜찮을 것 같습니다~ 현재 코드대로 머지하겠습니다!

2022-06-14 05:24 UTC, bigfanoftim requested changes

2022-06-14 05:24 UTC, bigfanoftim commented on jobs/views.py
> +        return JsonResponse({"message" : "FOLLOW_SUCCESS", "results" : results, "follow_count" : follow_count}, status =200)
```suggestion
        if Follow.objects.filter(user_id = user.id, job_id = job_id).exists(): 
            Follow.objects.get(user_id = user.id, job_id=job_id).delete()
            results = False
            message = "FOLLOW_DELETE"

        Follow.objects.create(
            user_id = user.id,
            job_id  = job_id,
        )
        message = "FOLLOW_SUCCESS"
        results = True
        follow_count = Follow.objects.filter(job_id=job_id).count()
        return JsonResponse({"message" : message, "results" : results, "follow_count" : follow_count}, status =200)
```

2022-06-14 08:42 UTC, jhwang0801 commented on jobs/views.py
> +        return JsonResponse({"message" : "FOLLOW_SUCCESS", "results" : results, "follow_count" : follow_count}, status =200)
수정 완료했습니다!

2022-06-14 09:24 UTC, bigfanoftim approved these changes
LGTM 👍

2022-06-14 09:24 UTC, merged